/// Phase 2 stub — ARKit + LiDAR indoor navigation
///
/// This file establishes the camera permission flow and live preview layer.
/// In Phase 2, ARKit world tracking and AVDepthData (LiDAR) will be layered on
/// top of this foundation to detect surfaces, doorways, and open corridors and
/// generate micro-waypoints for indoor navigation.
///
/// No architectural decisions here block ARKit integration:
/// - AVCaptureSession is separate from ARSession; swapping in will be additive.
/// - The delegate protocol is ready for AR state callbacks.
/// - LiDAR depth processing hooks are stubbed as clearly-marked TODOs.

import UIKit
import AVFoundation
import SwiftUI

// MARK: - Delegate protocol (Phase 2 will fill these out)

protocol CameraViewControllerDelegate: AnyObject {
    /// Called when a set of micro-waypoints is generated from depth analysis.
    func cameraViewController(_ vc: CameraViewController,
                               didGenerateMicroWaypoints waypoints: [MicroWaypoint])
    /// Called when an obstacle is detected within a given distance (metres).
    func cameraViewController(_ vc: CameraViewController,
                               didDetectObstacleAt distance: Float)
}

/// Lightweight indoor waypoint generated by LiDAR depth analysis.
struct MicroWaypoint {
    let relativeAngleDegrees: Float  // relative to phone forward axis
    let distanceMetres: Float
}

// MARK: - CameraViewController

class CameraViewController: UIViewController {

    weak var delegate: CameraViewControllerDelegate?

    // MARK: AVFoundation
    private var captureSession: AVCaptureSession?
    private var previewLayer: AVCaptureVideoPreviewLayer?

    // MARK: Phase 2 — ARKit / LiDAR (declared here so the compiler knows they exist)
    // private var arSession: ARSession?               // TODO Phase 2
    // private var arConfiguration: ARWorldTrackingConfiguration?  // TODO Phase 2

    // MARK: - Lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .black
        requestCameraPermission()
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        previewLayer?.frame = view.bounds
    }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        captureSession?.stopRunning()
    }

    // MARK: - Permissions

    private func requestCameraPermission() {
        switch AVCaptureDevice.authorizationStatus(for: .video) {
        case .authorized:
            setupCaptureSession()
        case .notDetermined:
            AVCaptureDevice.requestAccess(for: .video) { [weak self] granted in
                DispatchQueue.main.async {
                    if granted { self?.setupCaptureSession() }
                }
            }
        default:
            // Camera denied — navigation still works via audio; just skip preview.
            break
        }
    }

    // MARK: - Live preview

    private func setupCaptureSession() {
        let session = AVCaptureSession()
        session.sessionPreset = .high

        // Prefer LiDAR-equipped camera when available (iPhone 12 Pro+)
        let deviceType: AVCaptureDevice.DeviceType
        if #available(iOS 15.4, *),
           AVCaptureDevice.default(.builtInLiDARDepthCamera, for: .video, position: .back) != nil {
            deviceType = .builtInLiDARDepthCamera
        } else {
            deviceType = .builtInWideAngleCamera
        }

        guard
            let camera = AVCaptureDevice.default(deviceType, for: .video, position: .back),
            let input  = try? AVCaptureDeviceInput(device: camera),
            session.canAddInput(input)
        else { return }

        session.addInput(input)

        // TODO Phase 2: add AVCaptureDepthDataOutput here for LiDAR frames.
        // let depthOutput = AVCaptureDepthDataOutput()
        // depthOutput.setDelegate(self, callbackQueue: .global(qos: .userInitiated))
        // if session.canAddOutput(depthOutput) { session.addOutput(depthOutput) }

        let preview = AVCaptureVideoPreviewLayer(session: session)
        preview.videoGravity = .resizeAspectFill
        preview.frame = view.bounds
        view.layer.addSublayer(preview)
        previewLayer = preview
        captureSession = session

        DispatchQueue.global(qos: .userInitiated).async { session.startRunning() }
    }

    // MARK: - Phase 2 ARKit hooks (stubbed)

    // func startARSession() {
    //     guard ARWorldTrackingConfiguration.isSupported else { return }
    //     arConfiguration = ARWorldTrackingConfiguration()
    //     arConfiguration?.frameSemantics = [.sceneDepth]  // LiDAR
    //     arSession = ARSession()
    //     arSession?.delegate = self
    //     arSession?.run(arConfiguration!)
    // }

    // MARK: - Phase 2 depth processing (stubbed)

    // func processLiDARDepthMap(_ depthData: AVDepthData) { ... }
    // func generateIndoorMicrowaypoints(from frame: ARFrame) { ... }
}

// MARK: - SwiftUI Bridge

struct CameraView: UIViewControllerRepresentable {
    weak var delegate: CameraViewControllerDelegate?

    func makeUIViewController(context: Context) -> CameraViewController {
        let vc = CameraViewController()
        vc.delegate = delegate
        return vc
    }

    func updateUIViewController(_ uiViewController: CameraViewController, context: Context) {}
}
